INSERT INTO USER (USERNAME, PASSWORD) VALUES('user', '$2a$10$QZPaHODeA1mn1fQ.fdY12OZY659//v5S.E5J9XKjE.dexgCZLrMFK');
INSERT INTO USER (USERNAME, PASSWORD) VALUES('admin','$2a$10$QZPaHODeA1mn1fQ.fdY12OZY659//v5S.E5J9XKjE.dexgCZLrMFK');
INSERT INTO USER (USERNAME, PASSWORD) VALUES('prateek', '$2a$10$QZPaHODeA1mn1fQ.fdY12OZY659//v5S.E5J9XKjE.dexgCZLrMFK');


INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('prateek', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('prateek', 'ADMIN');